name: deploy
on:
  pull_request:
  push:
    branches: [master]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: gbp
        - name: xenial
        - name: bionic
        - name: focal
    steps:
    - uses: actions/checkout@v1
    - run: |
        docker build \
          --pull \
          --file dockerfiles/Dockerfile.${{ matrix.name }} \
          --tag docker.pkg.github.com/deadsnakes/runbooks/deadsnakes-${{ matrix.name }} \
          .
      name: build
    - run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u asottile --password-stdin && \
        docker push docker.pkg.github.com/deadsnakes/runbooks/deadsnakes-${{ matrix.name }}
      name: push
      if: github.event_name != 'pull_request'
