name: main

on:
  pull_request:
    paths: [dockerfiles/*, .github/workflows/main.yml, bin/docker-build]
  push:
    branches: [main]
    paths: [dockerfiles/*, .github/workflows/main.yml, bin/docker-build]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< "$GHCR_TOKEN"
      env:
        GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
    - run: docker buildx create --driver docker-container --use
    - run: python3 -uS bin/docker-build --event ${{ github.event_name }}
