on:
  workflow_call:
    inputs:
      dists-json:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.push.updated }}
    steps:
    - name: clone target
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: clone runbooks
      uses: actions/checkout@v3
      with:
        path: runbooks
        repository: deadsnakes/runbooks
    - name: pull upstream cpython
      run: runbooks/meta-gbp update
    - name: push changes
      id: push
      run: |
        if ! git diff --quiet HEAD origin/HEAD; then
            echo 'updated=true' >> "$GITHUB_OUTPUT"
            git push origin HEAD
        fi
  build:
    needs: update
    if: needs.outputs.updated == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{ fromJSON(inputs.dists-json) }}
    steps:
    - name: configure git
      run: |
        git config --global user.name 'Anthony Sottile (deadsnakes)'
        git config --global user.email 'asottile+deadsnakes@umich.edu'
        echo 'DEBFULLNAME=Anthony Sottile (deadsnakes)' >> $GITHUB_ENV
        echo 'DEBEMAIL=asottile+deadsnakes@umich.edu' >> $GITHUB_ENV
    - name: clone target
      uses: actions/checkout@v3
    - name: clone runbooks
      uses: actions/checkout@v3
      with:
        path: runbooks
        repository: deadsnakes/runbooks
    - name: import gpg key
      run: |
        install --directory ~/.gnupg --mode 700
        base64 -d <<< '${{ secrets.GPG_PUBLIC }}' > ~/.gnupg/pubring.gpg
        base64 -d <<< '${{ secrets.GPG_SECRET }}' > ~/.gnupg/secring.gpg
        chmod 600 ~/.gnupg/*
    - name: materialize
      run: runbooks/meta-gbp materialize ${{ matrix.name }}
    - name: build
      run: runbooks/meta-gbp build
    - name: test
      run: runbooks/quick-test --distrib-codename ${{ matrix.name }} --dist-dir dist --src-dir work
    - name: build source package
      run: runbooks/meta-gbp build --source
    - name: upload package
      run: runbooks/meta-gbp upload
